package race_weekend;

public interface RaceSimulatorConstants {
    double DEFAULT_PIT_STOP_SECONDS = 16.0;
    int TYRE_DURABILITY_PIT_THRESHOLD = 70;
    double WORN_TYRE_PIT_STOP_SECONDS = 22.0;
    double BOT_PIT_STOP_RANDOM_RANGE = 6.0;

    double WET_RAIN_PERFORMANCE_WEIGHT = 0.14;
    double DRY_RAIN_PERFORMANCE_WEIGHT = 0.04;

    double ENGINE_POWER_WEIGHT = 0.08;
    double TRANSMISSION_EFFICIENCY_WEIGHT = 0.35;
    double CHASSIS_HANDLING_WEIGHT = 0.25;
    double SUSPENSION_CORNER_WEIGHT = 0.20;
    double AERODYNAMICS_DOWNFORCE_WEIGHT = 0.18;
    double TYRE_GRIP_WEIGHT = 0.22;
    double ENGINE_QUALITY_WEIGHT = 0.25;
    double CHASSIS_QUALITY_WEIGHT = 0.25;

    int DEFAULT_PLAYER_ENGINEERS_SKILL = 56;
    double ENGINEERS_ACTION_BASE = 0.96;
    double ENGINEERS_ACTION_MAX_TEAM_SIZE = 4.0;
    double ENGINEERS_ACTION_BONUS = 0.06;
    double DEFAULT_PLAYER_PRINCIPAL_IMPACT = 0.55;
    double DEFAULT_PLAYER_TECHNICAL_DIRECTOR_IMPACT = 0.55;
    double STAFF_SKILL_NORMALIZER = 100.0;

    int MIN_TRACK_SECTIONS = 1;
    double DRY_WEATHER_DRIVER_WEIGHT = 0.75;
    double DRY_WEATHER_SECONDARY_DRIVER_WEIGHT = 0.25;
    double ENGINE_POWER_SETUP_DIVISOR = 12.0;
    double SETUP_MATCH_NORMALIZER = 100.0;
    double PLAYER_ELEVATION_DIVISOR = 1200.0;

    double PLAYER_CAR_NORMALIZER = 220.0;
    double TOTAL_PERFORMANCE_CAR_WEIGHT = 0.45;
    double TOTAL_PERFORMANCE_DRIVER_WEIGHT = 0.25;
    double TOTAL_PERFORMANCE_ENGINEERS_WEIGHT = 0.15;
    double TOTAL_PERFORMANCE_STAFF_WEIGHT = 0.10;
    double TOTAL_PERFORMANCE_SETUP_WEIGHT = 0.05;
    double STAFF_PRINCIPAL_WEIGHT = 0.45;
    double STAFF_TECHNICAL_DIRECTOR_WEIGHT = 0.55;

    double PLAYER_BASE_LAP_SECONDS = 55.0;
    double PLAYER_LAP_KM_FACTOR = 7.2;
    double PLAYER_PERFORMANCE_WINDOW_MIN = 0.84;
    double PLAYER_PERFORMANCE_BASELINE = 0.72;
    double PLAYER_PERFORMANCE_WINDOW_FACTOR = 0.35;
    double WEATHER_PENALTY_BASE = 1.0;
    double WEATHER_PENALTY_FACTOR = 0.35;
    double DEGRADATION_PENALTY_FACTOR = 0.025;
    double RANDOM_CENTER = 0.5;
    double CONSISTENCY_NOISE_BASE = 2.8;
    double CONSISTENCY_NOISE_SKILL_FACTOR = 0.02;
    double MIN_PLAYER_LAP_TIME = 62.0;
    double MAX_PLAYER_LAP_TIME = 125.0;

    double BOT_VIRTUAL_CAR_BASE = 0.80;
    double BOT_VIRTUAL_CAR_REPUTATION_DIVISOR = 220.0;
    double BOT_VIRTUAL_CAR_RANDOM_RANGE = 0.08;
    int DEFAULT_BOT_ENGINEERS_SKILL = 58;
    double BOT_ENGINEERS_ACTION_BASE = 0.95;
    double DEFAULT_BOT_PRINCIPAL_IMPACT = 0.58;
    double DEFAULT_BOT_TECHNICAL_DIRECTOR_IMPACT = 0.58;
    double BOT_VIRTUAL_DRIVER_BASE = 0.82;
    double BOT_VIRTUAL_DRIVER_REPUTATION_DIVISOR = 250.0;
    double BOT_VIRTUAL_DRIVER_RANDOM_RANGE = 0.06;
    double BOT_TRACK_BIAS_BASE = 0.96;
    double BOT_TRACK_BIAS_FACTOR = 0.05;
    double BOT_ELEVATION_DIVISOR = 1250.0;
    double BOT_BASE_LAP_SECONDS = 54.0;
    double BOT_LAP_KM_FACTOR = 6.8;
    double BOT_PERFORMANCE_WINDOW_MIN = 0.85;
    double BOT_PERFORMANCE_BASELINE = 0.76;
    double BOT_PERFORMANCE_WINDOW_FACTOR = 0.32;
    double BOT_LAP_NOISE_RANGE = 1.6;
    double MAX_BOT_LAP_TIME = 123.0;
}
